<?php

return [
    'Via Roma, 1',
    'Via Garibaldi, 5',
    'Corso Italia, 10',
    'Via Vittorio Emanuele, 12',
    'Via Cardinale Dusmet, 20',
    'Corso Sicilia, 30',
    'Via Etnea, 45',
    'Via Alessi, 2',
    'Via dei Crociferi, 15',
    'Corso Martiri della Libertà, 8',
    'Via Umberto I, 6',
    'Via Rapisardi, 22',
    'Viale della Libertà, 40',
    'Via Carlo Alberto, 18',
    'Via Leopardi, 9',
    'Via di Svevia, 25',
    'Via Verga, 14',
    'Corso Filippo Re, 35',
    'Via Mazzini, 7',
    "Via S. Francesco d'Assisi, 3",
    'Via Mascagni, 16',
    'Via Crociferi, 4',
    'Via XX Settembre, 27',
    'Via Marconi, 19',
    'Via Galileo Galilei, 17',
    'Corso Umberto, 23',
    'Via Leonardo da Vinci, 31',
    'Via Volta, 21',
    'Via Cavour, 33',
    'Via Monti, 37',
    'Via Donizetti, 24',
    'Via Bellini, 29',
    'Via San Giuliano, 120',
    'Via Crociferi, 34',
    'Via Santa Filomena, 56',
    'Via Pacini, 21',
    'Via Raddusa, 19',
    'Corso Sicilia, 145',
    "Via Sant'Agata, 4",
    'Via Dusmet, 51',
    'Via Etnea, 9',
    'Piazza Teatro Massimo, 38',
    'Via Castello Ursino, 60',
    'Via Domenico Tempio, 13',
    'Via Santa Maria di Betlem, 58',
    'Via San Camillo de Lellis, 86',
    "Via Sant'Orsola, 16",
    'Via Santa Barbara, 8',
    'Via San Berillo, 52',
    'Via dei Pescatori, 55',
    'Via della Fiera, 58',
    'Via dei Beati Paoli, 60'
];
