<?php

return [
    'Catania',
    'Acireale',
    'Paternò',
    'Misterbianco',
    'Mascalucia',
    'Giarre',
    'Gravina di Catania',
    'Tremestieri Etneo',
    'Aci Catena',
    'Caltagirone',
    'Adrano',
    'Belpasso',
    'Biancavilla',
    'Bronte',
    'Calatabiano',
    'Caltagirone',
    'Camporotondo Etneo',
    'Castel di Judica',
    'Castiglione di Sicilia',
    'Fiumefreddo di Sicilia',
    'Linguaglossa',
    'Mascali',
    'Milo',
    'Nicolosi',
    'Pedara',
    'Ragalna',
    'Ramacca',
    'Randazzo',
    'Riposto',
    'San Giovanni la Punta',
    'San Gregorio di Catania',
    "Sant'Agata li Battiati",
    'Santa Maria di Licodia',
    'Trecastagni',
    'Troina',
    'Viagrande',
    'Villafranca Tirrena',
    'Aci Bonaccorsi',
    'Aci Castello',
    "Aci Sant'Antonio",
    'Brucoli',
    'Carle',
    'ntini',
    'Fiumefreddo Bruzio',
    'Giarre-Riposto',
    'Lentini',
    'Maletto',
    'Militello in Val di Catania',
    'San Cono',
    'San Michele di Ganzaria',
    'Scordia'
];
